### PR TITLE
v-bind for passing paramentrs in multiselect

### PR DESCRIPTION
**Pull request by dormadekhin**

### CODE REVIEW

**Comment by Benjacho** [comment]
Hello what is the purpose to do that thing, you can pass options in options method.

**Comment by dormadekhin** [comment]
to pass other parameters, for example "selectLabel", "selectedLabel" and others

**Comment by Benjacho** [comment]
Nice feature, please can you add that to README? To know and use that properties

**Comment by dormadekhin** [comment]
I added a description of the method in Readme.md

**Pull request merged**
