### PR TITLE
make optionsLabel able to use nested object key

### PR DESCRIPTION
**Pull request by ahmedsayedabdelsalam**
I use spatie translation package and I think many of us do

the translation columns are of json datatype like name = {"en": "dog", "de": "hund"}

I find that the form select input works well but the index and details pages are not working `optionsLable('name')`
Screen Shot 2020-07-17 at 1 57 36 AM

also when setting optionsLabel like this `optionsLabel('name.en')`
Screen Shot 2020-07-17 at 1 57 17 AM

I know we could make a computed attribute for that but it's painful to add those custom attributes everywhere.

I think making it can access nested key from object like `optionsLabel('name.en')` well be very helpful
Screen Shot 2020-07-17 at 1 55 09 AM

### CODE REVIEW

**Comment by Benjacho** [comment]
First of all thank you for your contribution, could you make Readme about this? after that i will be able to merge this

**Comment by ahmedsayedabdelsalam** [comment]
> First of all thank you for your contribution, could you make Readme about this? after that i will be able to merge this

done ✅

**Comment by SimonBarrettACT** [comment]
This doesn't seem to fix the issue in FormView.

**Comment by ahmedsayedabdelsalam** [comment]
I managed to fix the form field issue this way

1- add a custom attribute to the model and add it to the $appends prop
`protected $appends = ['name_translated'];`
```
public function getNameTranslatedAttribute(){
    return $this->getTranslation('name', $this->getLocale());
}
```

2- add the filed to nova resource like this `->setPivot(['is_available' => true])`
```
BelongsToManyField::make('Available Specs', 'availableSpecifications', Specification::class)
                ->setMultiselectProps([
                    'closeOnSelect' => false,
                    // and others from docs (https://vue-multiselect.js.org/#sub-props)
                ])
                ->setPivot(['is_available' => true])
                ->optionsLabel('name_translated')
                ->showAsListInDetail()
                ->hideFromIndex(),

```

**Comment by ahmedsayedabdelsalam** [comment]
@SimonBarrettACT make sure you use the `LogsActivit` trait.
and add    `protected $translatable = ['title'];` to the model.
and make sure that the values used to represent the resource it `title`
Screen Shot 2020-08-27 at 5 16 37 PM
Screen Shot 2020-08-27 at 5 15 42 PM
Screen Shot 2020-08-27 at 5 15 00 PM

**Comment by SimonBarrettACT** [comment]
My model was already set up as you suggested and this is my field entry:

```php
BelongsToManyField::make('Towns', 'towns', 'App\Nova\Town')->optionsLabel('name.en')
```

but nothing is being displayed.

**Comment by SimonBarrettACT** [comment]
I'm not sure what you mean bu:

> [**@SimonBarrettACT**](https://github.com/SimonBarrettACT) make sure you use the `LogsActivit` trait.

**Comment by ahmedsayedabdelsalam** [comment]
Sorry, my mistake I meant the trait in the model as shown in the picture

I am not sure why it is not working with you
But I rechecked the code again an it's working with me.

**Comment by SimonBarrettACT** [comment]
It's strange. I can't see why it isn't working either. Thanks for your efforts to help though.

**Comment by ahmedsayedabdelsalam** [comment]
I wish I could help, 
can you send me those files to **e.eng.ahmedsayed@gmail.com** I'll try debugging this issue in my project? 
if you're ok with that.
I need those files.
models and nova resources for the two sides of the relation.

**Comment by LouisHrg** [comment]
Hello ! 
I tried your fork and it works well, except on editing, i don't have any label displayed
image

**Comment by ahmedsayedabdelsalam** [comment]
@LouisHrg 
at "create" form when you select something is it also appears like that?

**Comment by LouisHrg** [comment]
Nope it works fine, I'll try to fix the issue in a PR today

**Comment by SimonBarrettACT** [comment]
I was having the same issue and have submitted a pull request #54 that fixes the issue by providing the ability to set the language used.

**Comment by ahmedsayedabdelsalam** [comment]
> Nope it works fine, I'll try to fix the issue in a PR today, the issue seems to be in setInitialValue in FormField.vue
> 
> Update : here's the PR [ahmedsayedabdelsalam#1](https://github.com/ahmedsayedabdelsalam/belongs-to-many-field-nova/pull/1)
> 
> let me know 👍

@LouisHrg 
sorry for the late reply. your PR fixed the issue. Thank you.

@SimonBarrettACT kindly recheck if it works now.

**Comment by SimonBarrettACT** [comment]
It works for me thanks.

**Comment by ahmedsayedabdelsalam** [comment]
@SimonBarrettACT Great 👌

@Benjacho waiting for your review.

**Comment by manyasone** [comment]
Works perfectly fine for me, too. Any chance this will be merged to the main repo in the near future? ;)

**Comment by Benjacho** [comment]
Already merged ty

**Pull request closed without merging**
